---
- name: deploy
  hosts: all
  user: deploy
  vars_files:
    - vars/vars_prod.yml 
  tasks:
   
    # 
    # Register unix timestamp to mark current deployment version
    #
    - command: date +%s
      register: current_dir

    #     
    # Clone git repo into cache dir, they rsync to current_dir deploy version
    #
    - git: repo={{ gitrepo }} version={{ gitbranch }} dest={{ repo_cache }} update=yes
    - synchronize: src="{{ repo_cache }}/" dest={{ versions_dir }}/{{ current_dir.stdout }}

    #
    # Upload setup script into application version
    #
    - template: src=templates/sbin/setup.sh dest="{{ versions_dir }}/{{ current_dir.stdout }}/setup.sh" mode=0750

    #
    # Setup application before symlinking
    #
    - command: "{{ versions_dir }}/{{ current_dir.stdout }}/setup.sh"

    #
    # Point current symlink to current deploy version
    #
    - file: state=link src={{ versions_dir }}/{{ current_dir.stdout }} dest={{ project_dir }}/current

    #
    # Restart wsgi server with supervisord
    #
    - supervisorctl: name={{ app_name }}-wsgi state=restarted
      sudo: True

    #
    # Check and remove > num_deploys in the versions_dir 
    #
    - shell: ls -1 {{ versions_dir }} |  sort -n | tac
      register: last_deploy

    - file: state=absent recurse=yes path={{ versions_dir }}/{{ item }}
      with_items: last_deploy.stdout_lines[{{ num_deploys }}:]
