---
- name: deploy
  hosts: all
  vars: 
    project_dir: /tmp/test2
    versions_dir: /tmp/test2/versions
    cache_dir: /tmp/test2/cache
  tasks:
    - file: state=directory  dest={{ project_dir }}
    - file: state=directory  dest={{ versions_dir }}
    - file: state=directory  dest={{cache_dir}}
    - command: date +%s
      register: current_dir
    - file: name=previous state=absent
    - git: repo=https://github.com/brodul/yodl.git dest={{ cache_dir }}
    - synchronize: src={{ cache_dir }} dest={{ versions_dir }}/{{ current_dir.stdout }}
    - file: state=link src={{ versions_dir }}/{{ current_dir.stdout }} dest={{ project_dir }}/current
    - file: path={{ project_dir }}/current/yodl/media state=directory
    
    - shell: ls -1 {{ versions_dir }} |  sort -n | tac
      register: last_deploy

    - file: state=absent recurse=yes path={{ versions_dir }}/{{ item }}
      with_items: last_deploy.stdout_lines[5:]
