---
- name: deploy_setup 
  hosts: all
  user: deploy
  sudo: False
  vars_files:
    - vars/vars_prod.yml 
  tasks:
    #
    # Include tasks that setups needen program
    # packages and pyton packages (dev, python-virtualenv, etc...)
    #
    - include: common/packages.yml
    - include: common/python.yml
    #
    # After that, let's create app directory structure
    #
    - file: state=directory  dest={{ projects_root }} owner={{ ansible_env.USER }}
      sudo: True
    - file: state=directory  dest={{ project_dir }}
    - file: state=directory  dest={{ versions_dir }}
    - file: state=directory  dest={{ shared_dir }}
    - file: state=directory  dest={{ repo_cache }}
    - file: state=directory  dest={{ venv_dir }}
    - file: state=directory  dest={{ shared_var }}
    - file: state=directory  dest={{ shared_sbin }}

    #
    # Create any additional directories needed
    #
    # - file: state=directory  dest="{{ shared_dir }}/media"
   
    #
    # Setup known_host file, so git clone over ssh doesn't fails
    #
    - template: src=templates/ssh/known_hosts dest="/home/{{ ansible_env.USER }}/.ssh/known_hosts"
    
    #
    # Prepare shared virtualenv for application
    #
    - command: "virtualenv --no-site-packages {{ venv_dir }}"

    #
    # Configure supervisord to start serving application after deployment
    #
    - template: src=templates/supervisor/program.conf dest="/etc/supervisor/conf.d/{{ app_name }}.conf"
      sudo: True
